import {
  UploadFile as UploadFileIcon,
  Description as DescriptionIcon,
  History as HistoryIcon,
  Info as InfoIcon,
  Calculate as CalculateIcon,
  Insights as InsightsIcon,
  GetApp as GetAppIcon,
  TableChart as TableChartIcon,
  BarChart as BarChartIcon,
  SmartToy as SmartToyIcon,
  AccountBalance as AccountBalanceIcon,
  TuneOutlined as TuneIcon,
  AutoAwesome as AutoAwesomeIcon,
  Bolt as BoltIcon,
} from "@mui/icons-material";

// Configurable dashboard items - edit this array to add/remove/hide items
export const dashboardItems = [
  {
    key: "unified_pipeline",
    title: "Run Pipeline",
    description: "PDF → historical → forecast in one step",
    path: "/Pipeline",
    icon: AutoAwesomeIcon,
    color: "#FF5622",
    show: true,
  },
  {
    key: "faster_engine",
    title: "Faster Engine",
    description: "Upload PDFs and get a formula-linked Excel model in 1–4 minutes",
    path: "/FasterEngine",
    icon: BoltIcon,
    color: "#FFB300",
    show: true,
  },
  {
    key: "pdf_extractor",
    title: "PDF Extractor",
    description: "Upload statements and extract tables",
    path: "/PdfExtractor",
    icon: UploadFileIcon,
    color: "#1976d2",
    show: true,
  },
  {
    key: "statements",
    title: "Financial Statements",
    description: "Browse statement tables by year",
    path: "/statements",
    icon: DescriptionIcon,
    color: "#2e7d32",
    show: true,
  },
  {
    key: "historical",
    title: "Historical Data",
    description: "Review historical extractions",
    path: "/historical",
    icon: HistoryIcon,
    color: "#6a1b9a",
    show: true,
  },
  {
    key: "historical_ai_agent",
    title: "Historical AI Agent",
    description: "Generate and manage AI table extractions",
    path: "/HistoricalAIAgent",
    icon: SmartToyIcon,
    color: "#ff9800",
    show: true,
  },
  {
    key: "financial_model",
    title: "Financial Model",
    description: "Full forecasting model with assumptions editor",
    path: "/FinancialModel",
    icon: AccountBalanceIcon,
    color: "#1F559B",
    show: true,
  },
  {
    key: "assumptions_editor",
    title: "Assumptions",
    description: "Edit model drivers and auto-recalculate",
    path: "/assumptions",
    icon: TuneIcon,
    color: "#0A1E37",
    show: true,
  },
  {
    key: "notes",
    title: "Financial Notes",
    description: "Fetch & view note disclosures",
    path: "/FinancialNotes",
    icon: InfoIcon,
    color: "#ef6c00",
    show: true,
  },
  {
    key: "export_manager",
    title: "Export Manager",
    description: "Export financial statements and historical data",
    path: "/ExportManager",
    icon: GetAppIcon,
    color: "#d32f2f",
    show: true,
  },
  {
    key: "report_generator",
    title: "Report Generator",
    description: "Visual Chart Builder for Statements",
    path: "/ReportGenerator",
    icon: BarChartIcon,
    color: "#c2185b",
    show: true,
  },
  // Legacy pages — hidden from sidebar, still accessible by URL
  {
    key: "iscon_historical",
    title: "Income Statement Historical",
    description: "View P&L historical data table",
    path: "/IsConHistorical",
    icon: HistoryIcon,
    color: "#00695c",
    show: false,
  },
  {
    key: "forecast_lv1",
    title: "PL Forecasting Lv1",
    description: "Edit assumptions and recalc",
    path: "/ForecastingCalculationLv1",
    icon: InsightsIcon,
    color: "#7b1fa2",
    show: false,
  },
  {
    key: "forecast_lv3",
    title: "PL Forecasting Lv3",
    description: "Sales & gross margin modeling",
    path: "/ForecastingCalculationLv3",
    icon: InsightsIcon,
    color: "#455a64",
    show: false,
  },
  {
    key: "bs_historical",
    title: "BS Historical",
    description: "View balance sheet historical data",
    path: "/BSHistorical",
    icon: DescriptionIcon,
    color: "#4a148c",
    show: false,
  },
  {
    key: "bs_forecasting",
    title: "BS Forecasting",
    description: "View balance sheet forecasting data",
    path: "/BSForecasting",
    icon: InsightsIcon,
    color: "#1565c0",
    show: false,
  },
  {
    key: "financial_summary",
    title: "Financial Summary",
    description: "Unified Income Statement and Balance Sheet view",
    path: "/FinancialSummary",
    icon: TableChartIcon,
    color: "#0288d1",
    show: false,
  },
];

