import {
  UploadFile as UploadFileIcon,
  Description as DescriptionIcon,
  History as HistoryIcon,
  Info as InfoIcon,
  Calculate as CalculateIcon,
  Insights as InsightsIcon,
} from "@mui/icons-material";

// Configurable dashboard items - edit this array to add/remove/hide items
export const dashboardItems = [
  {
    key: "pdf_extractor",
    title: "PDF Extractor",
    description: "Upload statements and extract tables",
    path: "/PdfExtractor",
    icon: UploadFileIcon,
    color: "#1976d2",
    show: true,
  },
  {
    key: "statements",
    title: "Financial Statements",
    description: "Browse statement tables by year",
    path: "/statements",
    icon: DescriptionIcon,
    color: "#2e7d32",
    show: true,
  },
  {
    key: "historical",
    title: "Historical Data",
    description: "Review historical extractions",
    path: "/historical",
    icon: HistoryIcon,
    color: "#6a1b9a",
    show: true,
  },
  {
    key: "notes",
    title: "Financial Notes",
    description: "Fetch & view note disclosures",
    path: "/FinancialNotes",
    icon: InfoIcon,
    color: "#ef6c00",
    show: true,
  },
  {
    key: "iscon_historical",
    title: "PL Historical",
    description: "View P&L historical data table",
    path: "/IsConHistorical",
    icon: HistoryIcon,
    color: "#00695c",
    show: true,
  },
  {
    key: "forecast_lv1",
    title: "PL Forecasting Lv1",
    description: "Edit assumptions and recalc",
    path: "/ForecastingCalculationLv1",
    icon: InsightsIcon,
    color: "#7b1fa2",
    show: true,
  },
  {
    key: "forecast_lv3",
    title: "PL Forecasting Lv3",
    description: "Sales & gross margin modeling",
    path: "/ForecastingCalculationLv3",
    icon: InsightsIcon,
    color: "#455a64",
    show: true,
  },
  {
    key: "bs_historical",
    title: "BS Historical",
    description: "View balance sheet historical data",
    path: "/BSHistorical",
    icon: DescriptionIcon,
    color: "#4a148c",
    show: true,
  },
  {
    key: "bs_forecasting",
    title: "BS Forecasting",
    description: "View balance sheet forecasting data",
    path: "/BSForecasting",
    icon: InsightsIcon,
    color: "#1565c0",
    show: true,
  },
];

